<a href="https://colab.research.google.com/github/sketchydough/Pytorch-DL-Practice/blob/main/tensor_math_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor1=torch.tensor([1,2,3,4])
tensor2=torch.tensor([5,6,7,8])

In [3]:
#addition
tensor1+tensor2

tensor([ 6,  8, 10, 12])

In [4]:
#subtraction
tensor1-tensor2

tensor([-4, -4, -4, -4])

In [6]:
#addition longhand
torch.add(tensor1,tensor2)

tensor([ 6,  8, 10, 12])

In [8]:
#subtraction longhand
torch.sub(tensor2,tensor1)

tensor([4, 4, 4, 4])

In [9]:
#multiplicaiton
tensor1*tensor2

tensor([ 5, 12, 21, 32])

In [10]:
#multiplication longhand
torch.mul(tensor1,tensor2)

tensor([ 5, 12, 21, 32])

In [11]:
#division
tensor2/tensor1

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#division longhand
torch.div(tensor2,tensor1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
#remainders modulus
tensor2%tensor1

tensor([0, 0, 1, 0])

In [14]:
#remainder longhand
torch.remainder(tensor2,tensor1)

tensor([0, 0, 1, 0])

In [15]:
#exponents / power
torch.pow(tensor1,tensor2)

tensor([    1,    64,  2187, 65536])

In [20]:
#Reassignment
#tensor1=tensor1+tensor2
#tensor1

In [23]:
#reassignment longhand
tensor1.add_(tensor2)
tensor1

tensor([31, 38, 45, 52])