<a href="https://colab.research.google.com/github/sketchydough/Pytorch-DL-Practice/blob/main/tensor_reshape_slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#reshape & view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
#reshape if we dont know the no of items using -1

arr2=torch.arange(10)
arr2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2=arr2.reshape(2,-1)
arr2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
arr3=torch.arange(15)
arr3=arr3.reshape(-1,3)
arr3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [9]:
#view
arr4=torch.arange(10)
arr5=arr4.view(2,5)
arr5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
#reshape and view will update themselves everytime we make a change
arr4[0]=100
arr5

tensor([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [11]:
#slices

arr7=torch.arange(10)
arr7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#grab a specific item
arr7[7]

tensor(7)

In [17]:
#grab a slice
arr7=arr7.reshape(5,2)
arr7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [18]:
arr7[:,1]

tensor([1, 3, 5, 7, 9])

In [21]:
#return a column

arr7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])