<a href="https://colab.research.google.com/github/sketchydough/Pytorch-DL-Practice/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [7]:
#python lists

my_list=[1,2,23,45]
my_list

[1, 2, 23, 45]

In [6]:
#python multi-dimensional array

my_list=[[1,2,3],[4,5,6],[7,8,9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
#Numpy array

arr1=np.random.rand(3,4)
arr1

array([[0.69290221, 0.72762391, 0.65732361, 0.79480601],
       [0.30447527, 0.2860472 , 0.25207117, 0.66708517],
       [0.87710575, 0.05155122, 0.96147436, 0.5031968 ]])

In [9]:
arr1.dtype

dtype('float64')

In [10]:
#Tensors

arr2=torch.randn(3,4)
arr2

tensor([[ 3.0831, -0.5236,  1.7796,  1.1125],
        [-0.7801,  1.0168, -0.6764,  1.1439],
        [-0.3128, -0.3287, -0.6958,  1.8538]])

In [11]:
#3d array
arr3=torch.zeros(2,3,4)
arr3

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## create tensor out of numpy array
arr4=torch.tensor(arr1)
arr4

tensor([[0.6929, 0.7276, 0.6573, 0.7948],
        [0.3045, 0.2860, 0.2521, 0.6671],
        [0.8771, 0.0516, 0.9615, 0.5032]], dtype=torch.float64)